kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
 name: prod-mesh
 namespace: audit-cluster
spec:
 remote:
   addresses:
   - audit-mesh-ingress.prod-cluster.svc.cluster.local
   discoveryPort: 8188
   servicePort: 15443
 gateways:
   ingress:
     name: prod-mesh-ingress
   egress:
     name: prod-mesh-egress
 security:
   trustDomain: prod-mesh.local
   clientID: prod-mesh.local/ns/prod-cluster/sa/audit-mesh-egress-service-account
   certificateChain:
     kind: ConfigMap
     name: prod-mesh-ca-root-cert
