kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
 name: dc1-mesh
 namespace: dc2-istio-system
spec:
 remote:
   addresses:
   - ADDRESS
   discoveryPort: DISCOVERY_PORT
   servicePort: SERVICE_PORT
 gateways:
   ingress:
     name: dc1-mesh-ingress
   egress:
     name: dc1-mesh-egress
 security:
   trustDomain: dc1-mesh.local
   clientID: dc1-mesh.local/ns/dc1-istio-system/sa/dc2-mesh-egress-service-account
   certificateChain:
     kind: ConfigMap
     name: dc1-mesh-ca-root-cert